//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAChatBot.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBShoppingCart
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Sequence { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<System.DateTime> UpdatedDt { get; set; }
        public string Quantity { get; set; }
    }
}
